version: '3.8'

services:
  meu-banco-de-dados:
    image: postgres
    container_name: TCC_PostgreSQL_DB
    environment:
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: